version: "3"

services:
  backend:
    image: ryyankhan/back:latest
    container_name: jobportal_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: ryyankhan/front:latest
    container_name: jobportal_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
